apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: prometheus-ui
  template:
    metadata:
      labels:
        app: prometheus-ui
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus-ui
        ports:
        - containerPort: 80
