apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: masternginx
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: server1
        url: https://kubernetes.default.svc
        image: nginx:1.14.2
        port: "80"
      - cluster: server2
        url: https://A28F2B73B4094DA3943AA394EE4884F5.gr7.us-west-2.eks.amazonaws.com
        image: nginx:1.21.1
        port: "8080"
  template:
    metadata:
      name: '{{cluster}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/Venkat-Sudharsanam/test.git
        targetRevision: HEAD
        path: nginxhelm
        helm:
          releaseName: '{{image}}-nginx'
          parameters:
          - name: image
            value: '{{image}}'
          - name: port
            value: '{{port}}'  
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated: {}
