apiVersion: argoproj.io/v1alpha1
kind: Application
  name: try-prometheus
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: argocd
  source:
    helm:
      parameters:
      - name: image
        value: nginx:1.14.2
      - name: port
        value: 80
      releaseName: try-prometheus
    path: applicationsets
    repoURL: https://github.com/hegdeshashi/argocd-demo.git
