apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus #name of the appliaciton
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hegdeshashi/argocd-demo.git'
    targetRevision: HEAD
    path: sandbox/charts/prometheus
    helm:
      parameters:
        - name: livenessProbe.failureThreshold
          value: "7"
  destination:
    server: https://kubernetes.default.svc #name of the aks cluster as per ARGO CD
    namespace: monitoring
